apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 406073615446.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 406073615446.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: c705b329
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
